controller_list:
  - name: arm_pos_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6

arm_pos_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint1
    - Joint2
    - Joint3
    - Joint4
    - Joint5
    - Joint6
  gains:
    Joint1: {p: 0.2, i: 0.0, d: 0.0} 
    Joint2: {p: 0.2, i: 0.0, d: 0.0}
    Joint3: {p: 0.2, i: 0.0, d: 0.0}
    Joint4: {p: 0.2, i: 0.0, d: 0.0}
    Joint5: {p: 0.2, i: 0.0, d: 0.0}
    Joint6: {p: 0.2, i: 0.0, d: 0.0}


joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

