// Generated by gencpp from file frame_msgs/set_servo_as.msg
// DO NOT EDIT!


#ifndef FRAME_MSGS_MESSAGE_SET_SERVO_AS_H
#define FRAME_MSGS_MESSAGE_SET_SERVO_AS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32MultiArray.h>
#include <std_msgs/Float32MultiArray.h>
#include <std_msgs/UInt8MultiArray.h>
#include <std_msgs/UInt8MultiArray.h>

namespace frame_msgs
{
template <class ContainerAllocator>
struct set_servo_as_
{
  typedef set_servo_as_<ContainerAllocator> Type;

  set_servo_as_()
    : servo_target_angle()
    , servo_target_cycle()
    , servo_target_angle_u8()
    , servo_target_cycle_u8()  {
    }
  set_servo_as_(const ContainerAllocator& _alloc)
    : servo_target_angle(_alloc)
    , servo_target_cycle(_alloc)
    , servo_target_angle_u8(_alloc)
    , servo_target_cycle_u8(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _servo_target_angle_type;
  _servo_target_angle_type servo_target_angle;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _servo_target_cycle_type;
  _servo_target_cycle_type servo_target_cycle;

   typedef  ::std_msgs::UInt8MultiArray_<ContainerAllocator>  _servo_target_angle_u8_type;
  _servo_target_angle_u8_type servo_target_angle_u8;

   typedef  ::std_msgs::UInt8MultiArray_<ContainerAllocator>  _servo_target_cycle_u8_type;
  _servo_target_cycle_u8_type servo_target_cycle_u8;





  typedef boost::shared_ptr< ::frame_msgs::set_servo_as_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::frame_msgs::set_servo_as_<ContainerAllocator> const> ConstPtr;

}; // struct set_servo_as_

typedef ::frame_msgs::set_servo_as_<std::allocator<void> > set_servo_as;

typedef boost::shared_ptr< ::frame_msgs::set_servo_as > set_servo_asPtr;
typedef boost::shared_ptr< ::frame_msgs::set_servo_as const> set_servo_asConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::frame_msgs::set_servo_as_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::frame_msgs::set_servo_as_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::frame_msgs::set_servo_as_<ContainerAllocator1> & lhs, const ::frame_msgs::set_servo_as_<ContainerAllocator2> & rhs)
{
  return lhs.servo_target_angle == rhs.servo_target_angle &&
    lhs.servo_target_cycle == rhs.servo_target_cycle &&
    lhs.servo_target_angle_u8 == rhs.servo_target_angle_u8 &&
    lhs.servo_target_cycle_u8 == rhs.servo_target_cycle_u8;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::frame_msgs::set_servo_as_<ContainerAllocator1> & lhs, const ::frame_msgs::set_servo_as_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace frame_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::frame_msgs::set_servo_as_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::frame_msgs::set_servo_as_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::frame_msgs::set_servo_as_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::frame_msgs::set_servo_as_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::frame_msgs::set_servo_as_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::frame_msgs::set_servo_as_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::frame_msgs::set_servo_as_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47ff6d7a480da9dc74da49bb9bec5dcf";
  }

  static const char* value(const ::frame_msgs::set_servo_as_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47ff6d7a480da9dcULL;
  static const uint64_t static_value2 = 0x74da49bb9bec5dcfULL;
};

template<class ContainerAllocator>
struct DataType< ::frame_msgs::set_servo_as_<ContainerAllocator> >
{
  static const char* value()
  {
    return "frame_msgs/set_servo_as";
  }

  static const char* value(const ::frame_msgs::set_servo_as_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::frame_msgs::set_servo_as_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32MultiArray servo_target_angle\n"
"std_msgs/Float32MultiArray servo_target_cycle\n"
"std_msgs/UInt8MultiArray servo_target_angle_u8\n"
"std_msgs/UInt8MultiArray servo_target_cycle_u8\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
"================================================================================\n"
"MSG: std_msgs/UInt8MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"uint8[]           data          # array of data\n"
"\n"
;
  }

  static const char* value(const ::frame_msgs::set_servo_as_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::frame_msgs::set_servo_as_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo_target_angle);
      stream.next(m.servo_target_cycle);
      stream.next(m.servo_target_angle_u8);
      stream.next(m.servo_target_cycle_u8);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_servo_as_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::frame_msgs::set_servo_as_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::frame_msgs::set_servo_as_<ContainerAllocator>& v)
  {
    s << indent << "servo_target_angle: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.servo_target_angle);
    s << indent << "servo_target_cycle: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.servo_target_cycle);
    s << indent << "servo_target_angle_u8: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.servo_target_angle_u8);
    s << indent << "servo_target_cycle_u8: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.servo_target_cycle_u8);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRAME_MSGS_MESSAGE_SET_SERVO_AS_H
