// Generated by gencpp from file diffusion_policy/eef_pose_vel.msg
// DO NOT EDIT!


#ifndef DIFFUSION_POLICY_MESSAGE_EEF_POSE_VEL_H
#define DIFFUSION_POLICY_MESSAGE_EEF_POSE_VEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace diffusion_policy
{
template <class ContainerAllocator>
struct eef_pose_vel_
{
  typedef eef_pose_vel_<ContainerAllocator> Type;

  eef_pose_vel_()
    : eef_pose_vel()  {
    }
  eef_pose_vel_(const ContainerAllocator& _alloc)
    : eef_pose_vel(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _eef_pose_vel_type;
  _eef_pose_vel_type eef_pose_vel;





  typedef boost::shared_ptr< ::diffusion_policy::eef_pose_vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diffusion_policy::eef_pose_vel_<ContainerAllocator> const> ConstPtr;

}; // struct eef_pose_vel_

typedef ::diffusion_policy::eef_pose_vel_<std::allocator<void> > eef_pose_vel;

typedef boost::shared_ptr< ::diffusion_policy::eef_pose_vel > eef_pose_velPtr;
typedef boost::shared_ptr< ::diffusion_policy::eef_pose_vel const> eef_pose_velConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diffusion_policy::eef_pose_vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diffusion_policy::eef_pose_vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::diffusion_policy::eef_pose_vel_<ContainerAllocator1> & lhs, const ::diffusion_policy::eef_pose_vel_<ContainerAllocator2> & rhs)
{
  return lhs.eef_pose_vel == rhs.eef_pose_vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::diffusion_policy::eef_pose_vel_<ContainerAllocator1> & lhs, const ::diffusion_policy::eef_pose_vel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace diffusion_policy

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::diffusion_policy::eef_pose_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diffusion_policy::eef_pose_vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diffusion_policy::eef_pose_vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diffusion_policy::eef_pose_vel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diffusion_policy::eef_pose_vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diffusion_policy::eef_pose_vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diffusion_policy::eef_pose_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c78ea9f30900fd93d065f768bfb9ecc";
  }

  static const char* value(const ::diffusion_policy::eef_pose_vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c78ea9f30900fd9ULL;
  static const uint64_t static_value2 = 0x3d065f768bfb9eccULL;
};

template<class ContainerAllocator>
struct DataType< ::diffusion_policy::eef_pose_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diffusion_policy/eef_pose_vel";
  }

  static const char* value(const ::diffusion_policy::eef_pose_vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diffusion_policy::eef_pose_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] eef_pose_vel\n"
;
  }

  static const char* value(const ::diffusion_policy::eef_pose_vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diffusion_policy::eef_pose_vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.eef_pose_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct eef_pose_vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diffusion_policy::eef_pose_vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diffusion_policy::eef_pose_vel_<ContainerAllocator>& v)
  {
    s << indent << "eef_pose_vel[]" << std::endl;
    for (size_t i = 0; i < v.eef_pose_vel.size(); ++i)
    {
      s << indent << "  eef_pose_vel[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.eef_pose_vel[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIFFUSION_POLICY_MESSAGE_EEF_POSE_VEL_H
