// Generated by gencpp from file diffusion_policy/get_velocity_list.msg
// DO NOT EDIT!


#ifndef DIFFUSION_POLICY_MESSAGE_GET_VELOCITY_LIST_H
#define DIFFUSION_POLICY_MESSAGE_GET_VELOCITY_LIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace diffusion_policy
{
template <class ContainerAllocator>
struct get_velocity_list_
{
  typedef get_velocity_list_<ContainerAllocator> Type;

  get_velocity_list_()
    : velocity_list()  {
    }
  get_velocity_list_(const ContainerAllocator& _alloc)
    : velocity_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _velocity_list_type;
  _velocity_list_type velocity_list;





  typedef boost::shared_ptr< ::diffusion_policy::get_velocity_list_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diffusion_policy::get_velocity_list_<ContainerAllocator> const> ConstPtr;

}; // struct get_velocity_list_

typedef ::diffusion_policy::get_velocity_list_<std::allocator<void> > get_velocity_list;

typedef boost::shared_ptr< ::diffusion_policy::get_velocity_list > get_velocity_listPtr;
typedef boost::shared_ptr< ::diffusion_policy::get_velocity_list const> get_velocity_listConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diffusion_policy::get_velocity_list_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diffusion_policy::get_velocity_list_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::diffusion_policy::get_velocity_list_<ContainerAllocator1> & lhs, const ::diffusion_policy::get_velocity_list_<ContainerAllocator2> & rhs)
{
  return lhs.velocity_list == rhs.velocity_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::diffusion_policy::get_velocity_list_<ContainerAllocator1> & lhs, const ::diffusion_policy::get_velocity_list_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace diffusion_policy

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::diffusion_policy::get_velocity_list_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diffusion_policy::get_velocity_list_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diffusion_policy::get_velocity_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diffusion_policy::get_velocity_list_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diffusion_policy::get_velocity_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diffusion_policy::get_velocity_list_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diffusion_policy::get_velocity_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "857cfa79eed99d6668b53660789af2e6";
  }

  static const char* value(const ::diffusion_policy::get_velocity_list_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x857cfa79eed99d66ULL;
  static const uint64_t static_value2 = 0x68b53660789af2e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::diffusion_policy::get_velocity_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diffusion_policy/get_velocity_list";
  }

  static const char* value(const ::diffusion_policy::get_velocity_list_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diffusion_policy::get_velocity_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] velocity_list\n"
;
  }

  static const char* value(const ::diffusion_policy::get_velocity_list_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diffusion_policy::get_velocity_list_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_velocity_list_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diffusion_policy::get_velocity_list_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diffusion_policy::get_velocity_list_<ContainerAllocator>& v)
  {
    s << indent << "velocity_list[]" << std::endl;
    for (size_t i = 0; i < v.velocity_list.size(); ++i)
    {
      s << indent << "  velocity_list[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocity_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIFFUSION_POLICY_MESSAGE_GET_VELOCITY_LIST_H
