// Generated by gencpp from file diffusion_policy/joint_angles.msg
// DO NOT EDIT!


#ifndef DIFFUSION_POLICY_MESSAGE_JOINT_ANGLES_H
#define DIFFUSION_POLICY_MESSAGE_JOINT_ANGLES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace diffusion_policy
{
template <class ContainerAllocator>
struct joint_angles_
{
  typedef joint_angles_<ContainerAllocator> Type;

  joint_angles_()
    : joint_angles()  {
    }
  joint_angles_(const ContainerAllocator& _alloc)
    : joint_angles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _joint_angles_type;
  _joint_angles_type joint_angles;





  typedef boost::shared_ptr< ::diffusion_policy::joint_angles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diffusion_policy::joint_angles_<ContainerAllocator> const> ConstPtr;

}; // struct joint_angles_

typedef ::diffusion_policy::joint_angles_<std::allocator<void> > joint_angles;

typedef boost::shared_ptr< ::diffusion_policy::joint_angles > joint_anglesPtr;
typedef boost::shared_ptr< ::diffusion_policy::joint_angles const> joint_anglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diffusion_policy::joint_angles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diffusion_policy::joint_angles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::diffusion_policy::joint_angles_<ContainerAllocator1> & lhs, const ::diffusion_policy::joint_angles_<ContainerAllocator2> & rhs)
{
  return lhs.joint_angles == rhs.joint_angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::diffusion_policy::joint_angles_<ContainerAllocator1> & lhs, const ::diffusion_policy::joint_angles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace diffusion_policy

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::diffusion_policy::joint_angles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diffusion_policy::joint_angles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diffusion_policy::joint_angles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diffusion_policy::joint_angles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diffusion_policy::joint_angles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diffusion_policy::joint_angles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diffusion_policy::joint_angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11501c45f507c225d25f998a0b6418cd";
  }

  static const char* value(const ::diffusion_policy::joint_angles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11501c45f507c225ULL;
  static const uint64_t static_value2 = 0xd25f998a0b6418cdULL;
};

template<class ContainerAllocator>
struct DataType< ::diffusion_policy::joint_angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diffusion_policy/joint_angles";
  }

  static const char* value(const ::diffusion_policy::joint_angles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diffusion_policy::joint_angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joint_angles\n"
;
  }

  static const char* value(const ::diffusion_policy::joint_angles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diffusion_policy::joint_angles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joint_angles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diffusion_policy::joint_angles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diffusion_policy::joint_angles_<ContainerAllocator>& v)
  {
    s << indent << "joint_angles[]" << std::endl;
    for (size_t i = 0; i < v.joint_angles.size(); ++i)
    {
      s << indent << "  joint_angles[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint_angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIFFUSION_POLICY_MESSAGE_JOINT_ANGLES_H
